site_name: LAFABRIQUE.AI
site_description: A Journey Through Artificial Intelligence
site_url: https://lafabrique.ai

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.svg
  icon:
    logo: material/factory
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.tabs.link
  palette:
    - scheme: default
      primary: custom
      accent: custom

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - GIA: https://gia.lafabrique.ai/
  - Chat my Resume: https://huggingface.co/spaces/bauagonzo/chat-my-resume
  - Pastebin: https://pb.lafabrique.ai

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      draft_on_serve: true
      draft: true
      blog_toc: false
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_toc: true
      categories: true
      categories_name: Categories
      categories_toc: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
